[package]
name = "webserver"
version = "0.1.0"
authors = ["teruya <abas.trace.on@gmail.com>"]
edition = "2018"

[dependencies]
mio = "0.6.11"
regex = "1"
log = "0.4"
env_logger = "0.6.1"
failure = "0.1.5"
